#
# Autogenerated by Thrift Compiler (0.13.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec

import sys

from thrift.transport import TTransport
all_structs = []


class Operacion(object):
    """
    Attributes:
     - operando1
     - operando2
     - operador

    """


    def __init__(self, operando1=None, operando2=None, operador=None,):
        self.operando1 = operando1
        self.operando2 = operando2
        self.operador = operador

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.DOUBLE:
                    self.operando1 = iprot.readDouble()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.DOUBLE:
                    self.operando2 = iprot.readDouble()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRING:
                    self.operador = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('Operacion')
        if self.operando1 is not None:
            oprot.writeFieldBegin('operando1', TType.DOUBLE, 1)
            oprot.writeDouble(self.operando1)
            oprot.writeFieldEnd()
        if self.operando2 is not None:
            oprot.writeFieldBegin('operando2', TType.DOUBLE, 2)
            oprot.writeDouble(self.operando2)
            oprot.writeFieldEnd()
        if self.operador is not None:
            oprot.writeFieldBegin('operador', TType.STRING, 3)
            oprot.writeString(self.operador.encode('utf-8') if sys.version_info[0] == 2 else self.operador)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class DivisionPorCeroException(TException):
    """
    Attributes:
     - mensaje

    """


    def __init__(self, mensaje=None,):
        self.mensaje = mensaje

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRING:
                    self.mensaje = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('DivisionPorCeroException')
        if self.mensaje is not None:
            oprot.writeFieldBegin('mensaje', TType.STRING, 1)
            oprot.writeString(self.mensaje.encode('utf-8') if sys.version_info[0] == 2 else self.mensaje)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __str__(self):
        return repr(self)

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class MatrizNoCuadradaException(TException):
    """
    Attributes:
     - mensaje

    """


    def __init__(self, mensaje=None,):
        self.mensaje = mensaje

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRING:
                    self.mensaje = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('MatrizNoCuadradaException')
        if self.mensaje is not None:
            oprot.writeFieldBegin('mensaje', TType.STRING, 1)
            oprot.writeString(self.mensaje.encode('utf-8') if sys.version_info[0] == 2 else self.mensaje)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __str__(self):
        return repr(self)

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(Operacion)
Operacion.thrift_spec = (
    None,  # 0
    (1, TType.DOUBLE, 'operando1', None, None, ),  # 1
    (2, TType.DOUBLE, 'operando2', None, None, ),  # 2
    (3, TType.STRING, 'operador', 'UTF8', None, ),  # 3
)
all_structs.append(DivisionPorCeroException)
DivisionPorCeroException.thrift_spec = (
    None,  # 0
    (1, TType.STRING, 'mensaje', 'UTF8', None, ),  # 1
)
all_structs.append(MatrizNoCuadradaException)
MatrizNoCuadradaException.thrift_spec = (
    None,  # 0
    (1, TType.STRING, 'mensaje', 'UTF8', None, ),  # 1
)
fix_spec(all_structs)
del all_structs
